version: "2"
linters:
  default: all
  disable:
    - depguard
    - err113
    - exhaustruct
    - gci
    - gofumpt
    - goimports
    - lll
    - mnd
    - nilnil
    - nlreturn
    - noctx
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
issues:
  exclusion:
    rules:
      - path: _test\.go
        linters:
          - funlen
      - path: cli/
        linters:
          - gochecknoglobals
          - gochecknoinits
          - forbidigo
