linters:
  enable-all: true
  disable:
    - depguard
    - err113
    - exhaustruct
    - gci
    - gofumpt
    - goimports
    - lll
    - mnd
    - nilnil
    - nlreturn
    - noctx
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
    - path: cli/
      linters:
        - gochecknoglobals
        - gochecknoinits
        - forbidigo
